version: '3.8'
services:
  web-words:
    # build: ./web
    image: erickcernarequejo/295words-docker-web-words:${IMAGE_VERSION}
    container_name: web-words-app
    depends_on:
      - api
      - db
    ports:
      - 8080:80
    networks:
      - frontend
      - backend
  api:
    # build: ./api
    image: erickcernarequejo/295words-docker-api:${IMAGE_VERSION}
    container_name: backend-api-app
    depends_on:
      - db
    # ports:
    #   - 8080:8080
    networks:
      - backend
  db:
    # build: ./db
    image: postgres:15-alpine
    container_name: bd
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./db/words.sql:/docker-entrypoint-initdb.d/words.sql:ro
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
networks:
  frontend:
  backend: