version: '3.8'
services:
  web-words:
    # build: ./web
    image: erickcernarequejo/295words-docker-web-words:v1.0
    container_name: web-words-app
    # environment:
    #   - VIRTUAL_HOST=web.host.docker.internal.sslip.io
    #   - VIRTUAL_PORT=80
    depends_on:
      - api
      - db
    ports:
      - 8080:80
    networks:
      - frontend
      - backend
  api:
    # build: ./api
    image: erickcernarequejo/295words-docker-api:v1.0
    container_name: backend-api-app
    depends_on:
      - db
    # ports:
    #   - 8080:8080
    networks:
      - backend
  db:
    # build: ./db
    image: postgres:15-alpine
    container_name: bd
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - ./db/words.sql:/docker-entrypoint-initdb.d/words.sql:ro
      - postgres-data:/var/lib/postgresql/data
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - 80:80
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #   networks:
  #     - frontend
volumes:
  postgres-data:
networks:
  frontend:
  backend: