version: '3.8'
services:
  frontend-topics:
    # build: ./frontend
    image: erickcernarequejo/295topics-fullstack-frontend-topics:v1.0
    container_name: frontend-topics-app
    environment:
      - API_URI=http://backend-topics-app:5000/api/topics
    depends_on:
      - backend-topics
      - db
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
  backend-topics:
    # build: ./backend
    image: erickcernarequejo/295topics-fullstack-backend-topics:v1.0
    container_name: backend-topics-app
    env_file:
      - backend/.env.template
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - backend
  db:
    # build: ./db
    image: mongo
    container_name: bd
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:1.0.0-20-alpine3.18
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - backend
volumes:
  mongo-data:
networks:
  frontend:
  backend: